          name:                   vsongbook  # the name of the snap
          # version:              3.12.5  # the version of the snap
          version:                master
          version-script:         printf "`cat currentrelease | head -n 1 `-`git rev-list master --count`-` git -C . rev-parse --short HEAD`"

          summary:                Freedom to sing anywhere anytime - Songs of Worship, Nyimbo za Injili and more  # 79 char long summary
          description:            |
            vSongBook (Virtual Songbook) is a high quality, visual, open source tool to give users access to song lyrics of major worship and praise songbooks used in christian gatherings be it in church, weddings, funerals or anywhere where one feels like singing. Controls and wizards are available for users to:
            * Browse, edit, add, and delete songs
            * Search songs realtime
            * Adjust font types and sizes among other display preferences
            * Issue SQL queries and inspect the results
            * View songs in presentation mode for use over projector.
            vSongBook is all about giving users the freedom to sing anywhere anytime.
          confinement:            strict  # use "strict" to enforce system access only via declared interfaces

          grade:                  devel
          icon:                   images/vsongbook.png
          type:                   app

          apps:
            vsongbook:
              command:            desktop-launch $SNAP/bin/vsongbook
              desktop:            share/applications/vsongbook.desktop
              environment:
                DISABLE_WAYLAND:  1
                TMPDIR:           $XDG_RUNTIME_DIR
              plugs:
                - desktop
                - gsettings
                - home
                - unity7
                - wayland
                - x11
                - removable-media

          build-packages:
              - build-essential
              - g++
              - qtbase5-dev
              - qttools5-dev
              - qttools5-dev-tools
              - libsqlite3-dev
              - cmake
              - libsqlcipher-dev
              - libqcustomplot-dev

              - libqt5scintilla2-dev
              - git
          parts:
              vsongbook:
                  plugin:         cmake
                  configflags:    ["-DUSE_QT5=True", "-Dsqlcipher=1", "-Wno-dev","-DSQLITE_ENABLE_JSON1=1"]
                  source:         .
              desktop-qt5:
                build-packages:
                - qtbase5-dev
                - dpkg-dev
                - libgtk-3-dev
                make-parameters:
                - FLAVOR=qt5
                plugin:           make
                source:           https://github.com/ubuntu/snapcraft-desktop-helpers.git
                source-subdir:    qt
                stage-packages:
                - libxkbcommon0
                - ttf-ubuntu-font-family
                - dmz-cursor-theme
                - light-themes
                - adwaita-icon-theme
                - gnome-themes-standard
                - shared-mime-info
                - libgtk-3-0
                - libqt5gui5
                - libgdk-pixbuf2.0-0
                - libqt5svg5
                - appmenu-qt5
                - libglib2.0-bin
                - libgtk-3-bin
                - unity-gtk3-module
                - libappindicator3-1
                - locales-all
                - xdg-user-dirs
                - ibus-gtk3
                - libibus-1.0-5
              dump:
                  plugin:         dump
                  after:
                  - desktop-qt5
                  - vsongbook
                  stage-packages:
                  - libc6
                  - libgcc1
                  - libsqlite3-0
                  - libstdc++6
                  - libsqlcipher-dev
                  - libatk-adaptor
                  - libgail-common
                  - libgail-3-0
                  - libgail-3-dev
                  - libgail-dev
                  - qtwayland5
                  filesets:
                      wanted:
                      - bin/*
                      - share/*
                      - usr/lib/*.*
                      - usr/lib/*-linux-gnu*/libsqlcipher.so.0*
                      - usr/lib/*-linux-gnu*/libdb*
                      - usr/lib/*-linux-gnu*/libz.so*
                      - usr/lib/*-linux-gnu*/libatk*
                      - usr/lib/*-linux-gnu*/libgail*
                      - usr/lib/*-linux-gnu*/gtk-2.0/modules/*
                      - etc/X11/Xsession.d/90atk-adaptor
                      - usr/lib/gnome-settings-daemon-3.0/gtk-modules/at-spi2-atk.desktop
                      - usr/lib/unity-settings-daemon-1.0/gtk-modules/at-spi2-atk.desktop
                  prime:
                  - $wanted
